server:
  port: 8002

spring:
  application:
    name: customer-service
  profiles:
    active: local
  config:
    uri: http://localhost:8888

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.ashina.ecommerce: DEBUG
