server:
  port: 8003

spring:
  application:
    name: inventory-service
  profiles:
    active: local
  config:
    import: "configserver:"

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.ashina.ecommerce: DEBUG
