server:
  port: 8901

spring:
  application:
    name: identity-server
  profiles:
    active: local
  config:
    uri: http://localhost:8888

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.ashina.ecommerce: DEBUG
