spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

mongo:
  customer: mongodb://localhost:27018/customer
  product: mongodb://localhost:27018/product
