spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

mongo:
  customer: mongodb://localhost:27017/customer
  product: mongodb://localhost:27017/product
