server:
  port: 8001

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.elasticsearch.client.WIRE: trace
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
    org.ashina.ecommerce: DEBUG
