version: "3"

services:

  keycloak:
      image: quay.io/keycloak/keycloak:latest
      container_name: keycloak
      ports:
        - 8901:8080
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: postgres
        DB_PASSWORD: 1234
        DB_SCHEMA: public
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: 1234
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
