server:
  port: 8901

logging:
  level:
#    org.springframework.security: TRACE
#    org.springframework.security.oauth2: TRACE
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: TRACE
    org.ashina.ecommerce: DEBUG
